# Schema for configuration files of the Search API module.

search_api.settings:
  type: mapping
  label: 'Search API settings'
  mapping:
    cron_worker_runtime:
      type: integer
      label: '@todo Is this used anywhere?'
    cron_limit:
      type: integer
      label: 'Cron batch size'
    default_tracker:
      type: string
      label: 'The default tracker plugin'

search_api.server.*:
  type: mapping
  label : 'Search server'
  mapping:
    machine_name:
      type: string
      label: 'Machine name'
    name:
      type: label
      label: Name'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: text
      label: 'Description'
    status:
      type: boolean
      label: 'Status'
    backendPluginId:
      type: string
      label: 'Backend Plugin ID'
    backendPluginConfig:
      type: search_api.backend.plugin.[%parent.backendPluginId]
    langcode:
      type: string
      label: 'Language code'

search_api.index.*:
  type: mapping
  label : 'Search index'
  mapping:
    machine_name:
      type: string
      label: 'Machine name'
    name:
      type: label
      label: Name'
    uuid:
      type: string
      label: 'UUID'
    description:
      type: text
      label: 'Description'
    readOnly:
      type: boolean
      label: 'Read-only'
    options:
      type: mapping
      label: 'Options'
      mapping:
        cron_limit:
          type: integer
          label: 'Cron batch size'
        index_directly:
          type: boolean
          label: 'Index items immediately'
    datasourcePluginIds:
      type: sequence
      label: 'Datasource plugin IDs'
      sequence:
        - type: string
    # How to do this properly?
    #datasourcePluginConfigs:
    #  type: mapping
    trackerPluginId:
      type: string
      label: 'Tracker plugin ID'
    trackerPluginConfig:
      type: search_api.tracker.plugin.[%parent.trackerPluginId]
    serverMachineName:
      type: string
      label: 'Server machine name'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Language code'
