# Schema for the configuration files of the Search API DB module.

search_api_db.settings:
  type: mapping
  label: 'Search API DB settings'
  mapping:
    autocomplete_max_occurrences:
      type: float
      label: 'Maximum occurences of a term until autocomplete suggestions ignores it'
